openapi: 3.0.0
info:
  title: API's dos Produtos e Serviços
  description: As API's descritas neste documento são referentes as API's da Produtos e Serviços do Open Banking Brasil.
  version: 1.0.0
servers:
  - url: http://api.banco.com.br/open-banking
paths:
  /products/v1/personal-accounts:
    get:
      tags:
      - "Products"
      summary: Obtém os dados da conta Pessoa Física.
      responses:
        '200':
          description: Uma conta pessoa física de uma instituição financeira.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/'
 