openapi: 3.0.0
info:
  title: API's OpenData do Open Banking Brasil
  description: As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
  version: 1.0.0
servers:
  - url: http://api.banco.com.br/open-banking/product-services/v1
  
###############
## Endpoints ##
###############
paths:
  /personal-account:
    get:
      tags:
      - "Accounts"
      summary: ""
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponsePersonalAccountsList'
 