type: object
description: Meta informações referente a API requisitada.
required:
  - requestDateTime
  - totalRecords
  - totalPages
properties:
  requestDateTime:
    description: 'Data e hora da consulta, conforme especificação RFC-3339, formato UTC.'
    type: "string"
    maxLength: 20
    format: "date-time"
    example: '2021-05-21T08:30:00Z'
  totalRecords:
    type: integer
    format: int32
    description: Número total de registros no resultado
    example: 1
  totalPages:
    type: integer
    format: int32
    description: Número total de páginas no resultado
    example: 1
  requestDateTime:
    description: "Data e hora de processamento a requisição. Uma string com data e hora conforme especificação RFC-3339, sempre com a utilização de timezone UTC(UTC time format)."
    type: "string"
    maxLength: 20
    format: "date-time"
    example: '2021-05-21T08:30:00Z'
additionalProperties: false