openapi: 3.0.0
info:
  title: API's OpenData do Open Banking Brasil
  description: As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
  version: 1.0.0-rc
  contact:
    email: apiteam@swagger.io
servers:
  - url: http://api.banco.com.br/open-banking/customers/v1
tags:
  - name: Customers
    description: Operações para listagem das informações Cadastrais do Cliente
paths:
  /credit-cards/identification:
    get:
      tags:
        - Credit Card Accounts
      summary: Obtém a identificação de Cartão de crédito.
      description: Método para obter a identificação de cartão de crédito.
      operationId: getCreditCardAccountsIdentification
      parameters:
        - $ref: ./parameters/Page.yaml
        - $ref: ./parameters/PageSize.yaml
      responses:
        '200':
          description: Dados sobre identificação de cartão de crédito
          content:
            application/json:
              schema:
                $ref: ./schemas/credit_cards_apis/ResponseCreditCardAccountsIdentification.yaml
