name: Stoplight

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - name: Spectral Linting
        uses: stoplightio/spectral-action@v0.6.1
        with:
          file_glob: 'documentation/source/swagger/*.yaml'
